name: deploy
on: [push]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3 
      - name: Set environment variable
        run: echo -e "PORT=8081" >> .env
      - name: update dependencies
        run: npm install
      - name: run pm2
        run: pm2 restart wa-blast-backend
