name: deploy
on: [push]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3 
      - name: update dependencies
        run: npm install
      - name: run pm2
        run: pm2 restart wa-blast-backend
